### ISSUE TITLE
Support: attachments - multiple files aren"t sent, only first

### ISSUE THREAD

**Issue by sorooris** [satoshilabs/trezor.io#104]
Only first file in the attachment is sent, other files are ignored completely.

![image](https://user-images.githubusercontent.com/10185314/55175059-e4ed5900-517e-11e9-9176-e1777232ef89.png)

**Comment by yohaaan** [comment]
Additional info:

It's possible to send a reply that includes multiple attachments as a support agent (tested).

Freshdesk should be supporting this feature.
