### ISSUE TITLE
Firefox - navbar moves when scrolling

### ISSUE THREAD

**Issue by sorooris** [satoshilabs/trezor.io#118]
Firefox (latest)

Navigation bar is docked to the upper part of the screen and moves when scrolling.

![image](https://user-images.githubusercontent.com/10185314/55730769-3fa57100-5a19-11e9-902d-30f734e119ae.png)

**Comment by keip** [comment]
48eac06e0a24a3b00535b7d29814de15a5977f52

**Comment by sorooris** [comment]
test OK

**Comment by sorooris** [comment]
test OK
