### ISSUE TITLE
[Support Center] Add link to Bitcoin StackExchange

### ISSUE THREAD

**Issue by prusnak** [satoshilabs/trezor.io#13]
https://trezor.io/support/ should contain link to StackOverflow somewhere:

```
https://bitcoin.stackexchange.com/questions/ask?tags=trezor
```

**Comment by runn1ng** [comment]
note - it's not StackOverflow but a bitcoin sub-SE site, that has different moderators/rules etc.

**Comment by prusnak** [comment]
Implemented but @chren-de-large forgot to close the ticket. Closing
