### ISSUE TITLE
Gap limit increase

### ISSUE THREAD

**Issue by LStella** [satoshilabs/trezor.io#37]
It would be a good feature to have the option to request a larger gap limit for Bitcoin address derivation and subscription for notifications. This is one of the main reasons we use electrum. When using a Trezor master public key as a merchant (for example using BTCpay server) there are often a lot of bitcoin addresses generated that are never used, so then the Trezor.io wallet does not discover them and we are not able to spend them from the Trezor web wallet.

Perhaps it is not possible to do this with the Insight software, but if possible it could be an advanced feature given that it requires more ressources.

To fix this issue, it is possible to consolidate all the inputs in electrum by sending the entirety of the balance to the last receiving address and they will appear in the Trezor web wallet.

**Comment by prusnak** [comment]
We won't be changing the gap limit, because it increased the server requirements. As you mentioned, workaround is to use Electrum. Another good fix would be if BTCpay started to fill in the unused addresses after some time.
