### ISSUE TITLE
Make testimonials more trusted

### ISSUE THREAD

**Issue by dorianpodulka** [satoshilabs/trezor.io#76]
Testimonials should look like tweets and they should be real (real name and real text)

**Comment by keip** [comment]
<img width="1306" alt="tinygrab screen shot 26-02-2019 15 06 55" src="https://user-images.githubusercontent.com/1011630/53418511-441d4980-39d8-11e9-8d99-c4ad115024fa.png">

**Comment by keip** [comment]
Get some real tweets from Marketing.

**Comment by sorooris** [comment]
test OK
