### ISSUE TITLE
Update Menu

### ISSUE THREAD

**Issue by dorianpodulka** [satoshilabs/trezor.io#77]
![image](https://user-images.githubusercontent.com/7957215/53019707-a1a01c00-3455-11e9-958c-e000ece752ff.png)

**Comment by dorianpodulka** [comment]
links:
home, wallet, blog, wiki, support, eshop

**Comment by keip** [comment]
<img width="1235" alt="tinygrab screen shot 19-02-2019 16 34 31" src="https://user-images.githubusercontent.com/1011630/53026954-46295a80-3464-11e9-9567-d62a98e65636.png">

**Comment by keip** [comment]
Make it green also on the dark header
<img width="922" alt="tinygrab screen shot 01-03-2019 14 01 54" src="https://user-images.githubusercontent.com/1011630/53639834-a5d4f200-3c2a-11e9-9391-fbe53484d0bf.png">

**Comment by keip** [comment]
set active

**Comment by sorooris** [comment]
test OK
