### ISSUE TITLE
Config information table

### ISSUE THREAD

**Issue by yohaaan** [satoshilabs/trezor.io#89]
Config information is located directly below the question (between the question and the answers). I would prefer the answers to be located directly below the question so it's more clear for the user.

![image](https://user-images.githubusercontent.com/37402530/54752271-c36bfa80-4bdd-11e9-88e1-b166f20e78a1.png)

**Comment by keip** [comment]
So after consultation. 
The device detection will be there only on the first step and there will be no options until you detect your device or click on "can't be detected" button.
After click on "can't be detected" button or detecting device the options will appear (if device is detected some issues can be filtered out based on device details).
