### ISSUE TITLE
Support: link to privacy policy

### ISSUE THREAD

**Issue by keip** [satoshilabs/trezor.io#98]
Right now the link to privacy policy goes to kayako: https://www.kayako.com/about/privacy

Maybe we should create a new page with our privacy policies on trezor.io

Open link in new tab.

**Comment by yohaaan** [comment]
replace with Freshdesk privacy policy link that is: https://www.freshworks.com/privacy/

Since this is a 3rd party app we're using and paying for I'd prefer to include their privacy policy (we don't have control over data that are processed by Freshdesk's administrator)
